_:
{
  homebrew.enable = true;
  homebrew.global.autoUpdate = true;
  homebrew.onActivation = {
    autoUpdate = true;
    upgrade = true;
    cleanup = "uninstall";
  };
  homebrew.taps = [
    "borgbackup/tap"
    "homebrew/cask-drivers"
    "homebrew/cask-fonts"
    "homebrew/cask-versions"
    "homebrew/cask"
    "homebrew/services"
    "messense/macos-cross-toolchains"
    "minio/stable"
    "mongodb/brew"
    "photonquantum/tap"
  ];
  homebrew.brews = [
    "autoconf"
    "borgbackup-fuse"
    "cmake"
    "dlib"
    "ffmpegthumbnailer"
    "jdupes"
    "libpng"
    "messense/macos-cross-toolchains/x86_64-unknown-linux-musl"
    "miniserve"
    "pdm"
    "pg_cron"
    "pipenv"
    "pipx"
    "pnpm"
    "sqlx-cli"
    "terminal-notifier"
    "textidote"
  ];
  homebrew.casks = [
    "1password-cli"
    "1password"
    "adguard"
    "adobe-acrobat-reader"
    "apache-directory-studio"
    "backuploupe"
    "cheatsheet"
    "clashx-pro"
    "deepl"
    "discord"
    "dropbox"
    "font-iosevka-nerd-font"
    "github"
    "grammarly-desktop"
    "handbrake"
    "iina"
    "jetbrains-toolbox"
    "karabiner-elements"
    "keka"
    "kekaexternalhelper"
    "keyboard-lock"
    "keycastr"
    "latest"
    "macfuse"
    "macgpt"
    "mactex"
    "malus"
    "mathpix-snipping-tool"
    "monitorcontrol"
    "nightowl"
    "notion"
    "obs"
    "openinterminal"
    "orbstack"
    "paw"
    "phoenix"
    "postman"
    "qlmarkdown"
    "qq"
    "racket"
    "raycast"
    "rectangle"
    "setapp"
    "shottr"
    "slidepilot"
    "squirrel"
    "steam"
    "syntax-highlight"
    "tencent-meeting"
    "tg-pro"
    "tunnelblick"
    "typora"
    "visual-studio-code"
    "vlc"
    "vorta"
    "zoom"
    "zotero"
    # "bartender" // managed by setapp
  ];
}
