# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  fish_abbreviation_tips = {
    pname = "fish_abbreviation_tips";
    version = "8ed76a62bb044ba4ad8e3e6832640178880df485";
    src = fetchFromGitHub {
      owner = "Gazorby";
      repo = "fish-abbreviation-tips";
      rev = "8ed76a62bb044ba4ad8e3e6832640178880df485";
      fetchSubmodules = false;
      sha256 = "sha256-F1t81VliD+v6WEWqj1c1ehFBXzqLyumx5vV46s/FZRU=";
    };
    date = "2023-01-23";
  };
  fish_async_prompt = {
    pname = "fish_async_prompt";
    version = "4c732cc043b8dd04e64a169ec6bbf3a9b394819f";
    src = fetchFromGitHub {
      owner = "acomagu";
      repo = "fish-async-prompt";
      rev = "4c732cc043b8dd04e64a169ec6bbf3a9b394819f";
      fetchSubmodules = false;
      sha256 = "sha256-YgqZINmY4nKphlqwHo2B0NfP4nmSxIIuAMUuoftI9Lg=";
    };
    date = "2023-02-26";
  };
  fish_autopairs = {
    pname = "fish_autopairs";
    version = "4d1752ff5b39819ab58d7337c69220342e9de0e2";
    src = fetchFromGitHub {
      owner = "jorgebucaran";
      repo = "autopair.fish";
      rev = "4d1752ff5b39819ab58d7337c69220342e9de0e2";
      fetchSubmodules = false;
      sha256 = "sha256-qt3t1iKRRNuiLWiVoiAYOu+9E7jsyECyIqZJ/oRIT1A=";
    };
    date = "2022-07-04";
  };
  fish_brew = {
    pname = "fish_brew";
    version = "328fc82e1c8e6fd5edc539de07e954230a9f2cef";
    src = fetchFromGitHub {
      owner = "oh-my-fish";
      repo = "plugin-brew";
      rev = "328fc82e1c8e6fd5edc539de07e954230a9f2cef";
      fetchSubmodules = false;
      sha256 = "sha256-ny82EAz0K4XYASEP/K8oxyhyumrITwC5lLRd+HScmNQ=";
    };
    date = "2023-05-11";
  };
  fish_done = {
    pname = "fish_done";
    version = "eb32ade85c0f2c68cbfcff3036756bbf27a4f366";
    src = fetchFromGitHub {
      owner = "franciscolourenco";
      repo = "done";
      rev = "eb32ade85c0f2c68cbfcff3036756bbf27a4f366";
      fetchSubmodules = false;
      sha256 = "sha256-DMIRKRAVOn7YEnuAtz4hIxrU93ULxNoQhW6juxCoh4o=";
    };
    date = "2024-04-11";
  };
  fish_jump = {
    pname = "fish_jump";
    version = "af285ff91fa9d0d0261b810e09f8a4a05a6b1307";
    src = fetchFromGitHub {
      owner = "oh-my-fish";
      repo = "plugin-jump";
      rev = "af285ff91fa9d0d0261b810e09f8a4a05a6b1307";
      fetchSubmodules = false;
      sha256 = "sha256-MVIXBKsfd7rrH7Dh7cksNI29YunqAGZvuZwdfrf1bZQ=";
    };
    date = "2021-02-14";
  };
  fish_puffer_fish = {
    pname = "fish_puffer_fish";
    version = "12d062eae0ad24f4ec20593be845ac30cd4b5923";
    src = fetchFromGitHub {
      owner = "nickeb96";
      repo = "puffer-fish";
      rev = "12d062eae0ad24f4ec20593be845ac30cd4b5923";
      fetchSubmodules = false;
      sha256 = "sha256-2niYj0NLfmVIQguuGTA7RrPIcorJEPkxhH6Dhcy+6Bk=";
    };
    date = "2024-03-03";
  };
  fish_sponge = {
    pname = "fish_sponge";
    version = "384299545104d5256648cee9d8b117aaa9a6d7be";
    src = fetchFromGitHub {
      owner = "meaningful-ooo";
      repo = "sponge";
      rev = "384299545104d5256648cee9d8b117aaa9a6d7be";
      fetchSubmodules = false;
      sha256 = "sha256-MdcZUDRtNJdiyo2l9o5ma7nAX84xEJbGFhAVhK+Zm1w=";
    };
    date = "2022-10-05";
  };
  fish_sudope = {
    pname = "fish_sudope";
    version = "83919a692bc1194aa322f3627c859fecace5f496";
    src = fetchFromGitHub {
      owner = "oh-my-fish";
      repo = "plugin-sudope";
      rev = "83919a692bc1194aa322f3627c859fecace5f496";
      fetchSubmodules = false;
      sha256 = "sha256-pD4rNuqg6TG22L9m8425CO2iqcYm8JaAEXIVa0H/v/U=";
    };
    date = "2021-04-11";
  };
  sbarlua = {
    pname = "sbarlua";
    version = "437bd2031da38ccda75827cb7548e7baa4aa9978";
    src = fetchFromGitHub {
      owner = "FelixKratz";
      repo = "SbarLua";
      rev = "437bd2031da38ccda75827cb7548e7baa4aa9978";
      fetchSubmodules = false;
      sha256 = "sha256-F0UfNxHM389GhiPQ6/GFbeKQq5EvpiqQdvyf7ygzkPg=";
    };
    date = "2024-08-12";
  };
  yazi_flavors = {
    pname = "yazi_flavors";
    version = "c8771150b8e9d8cc1d2e44b74f4c87d0324b25d9";
    src = fetchFromGitHub {
      owner = "PhotonQuantum";
      repo = "flavors";
      rev = "c8771150b8e9d8cc1d2e44b74f4c87d0324b25d9";
      fetchSubmodules = false;
      sha256 = "sha256-CoJXv15lPCVW7qyXd2Csj2ltFELlGkN6PKY5Iz6Md70=";
    };
    date = "2025-01-17";
  };
  yazi_plugins = {
    pname = "yazi_plugins";
    version = "e4aaf430ad7f81d2e358e3a60525c8ef3fa259fc";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "e4aaf430ad7f81d2e358e3a60525c8ef3fa259fc";
      fetchSubmodules = false;
      sha256 = "sha256-dIj2YgLN04nFxmw7I/sdbJY2QCs+Nmb4eUtfLlPL53E=";
    };
    date = "2025-01-17";
  };
  yazi_relative_motions = {
    pname = "yazi_relative_motions";
    version = "df97039a04595a40a11024f321a865b3e9af5092";
    src = fetchFromGitHub {
      owner = "dedukun";
      repo = "relative-motions.yazi";
      rev = "df97039a04595a40a11024f321a865b3e9af5092";
      fetchSubmodules = false;
      sha256 = "sha256-csX8T2a5f7k6g2mlR+08rm0qBeWdI4ABuja+klIvwqw=";
    };
    date = "2024-12-02";
  };
  yazi_starship = {
    pname = "yazi_starship";
    version = "4053c8c486f9cfd60f1f42fa5d80e97caef41eb1";
    src = fetchFromGitHub {
      owner = "Rolv-Apneseth";
      repo = "starship.yazi";
      rev = "4053c8c486f9cfd60f1f42fa5d80e97caef41eb1";
      fetchSubmodules = false;
      sha256 = "sha256-KTN3gf3VFGlBxgsQFMa/fdhoovapXo0X65IJjXcl98A=";
    };
    date = "2025-01-08";
  };
  zimfw_completion = {
    pname = "zimfw_completion";
    version = "8a73f55e7ab0077ed34bfc3cb4db4e71afb7d952";
    src = fetchFromGitHub {
      owner = "zimfw";
      repo = "completion";
      rev = "8a73f55e7ab0077ed34bfc3cb4db4e71afb7d952";
      fetchSubmodules = false;
      sha256 = "sha256-/UC+tLYInJD+RfTtasWNnOPXES1ucAPhWgY8Zej5NWk=";
    };
    date = "2024-10-21";
  };
  zimfw_git = {
    pname = "zimfw_git";
    version = "7a57a6e85b316c8a3a1dc47d5420958655044f18";
    src = fetchFromGitHub {
      owner = "zimfw";
      repo = "git";
      rev = "7a57a6e85b316c8a3a1dc47d5420958655044f18";
      fetchSubmodules = false;
      sha256 = "sha256-SprVNI3AKuw/XTOnJ0KgT9Tb2SxTmOb2QibsyZEYFg8=";
    };
    date = "2024-06-10";
  };
  zimfw_input = {
    pname = "zimfw_input";
    version = "b2a8a80071dc781dd1b075a5161d2a0225140916";
    src = fetchFromGitHub {
      owner = "zimfw";
      repo = "input";
      rev = "b2a8a80071dc781dd1b075a5161d2a0225140916";
      fetchSubmodules = false;
      sha256 = "sha256-alS02tiio5hfNviAdJ/uOhoNs4ESr7+dxLaJIY4Os3A=";
    };
    date = "2023-08-10";
  };
  zimfw_utility = {
    pname = "zimfw_utility";
    version = "fec84342585d61dff448c786ad4eeb082c450c54";
    src = fetchFromGitHub {
      owner = "zimfw";
      repo = "utility";
      rev = "fec84342585d61dff448c786ad4eeb082c450c54";
      fetchSubmodules = false;
      sha256 = "sha256-XLuEEviudKNhAA9V0oqVlxvXdtXknoCXQlU2lF9mr1Q=";
    };
    date = "2024-10-01";
  };
  zsh_completions = {
    pname = "zsh_completions";
    version = "a7f01622f7bc6941d1c6297be6995fe1bbc9d4de";
    src = fetchFromGitHub {
      owner = "zsh-users";
      repo = "zsh-completions";
      rev = "a7f01622f7bc6941d1c6297be6995fe1bbc9d4de";
      fetchSubmodules = false;
      sha256 = "sha256-lDlXqMHYHlX0RKFhCNjGwxsng0DI8+ErLWNGHLblsAw=";
    };
    date = "2025-01-12";
  };
}
