# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ani-rss = {
    pname = "ani-rss";
    version = "v3.1.68";
    src = fetchurl {
      url = "https://github.com/wushuo894/ani-rss/releases/download/v3.1.68/ani-rss.jar";
      name = "ani-rss.jar";
      sha256 = "sha256-Q0kBEXQHJKiJo3VUbSmcSfTiQLX57GxKhX23qeHkTAw=";
    };
  };
  emby = {
    pname = "emby";
    version = "4.9.5.0";
    src = fetchurl {
      url = "https://github.com/MediaBrowser/Emby.Releases/releases/download/4.9.5.0/emby-server-deb_4.9.5.0_amd64.deb";
      name = "emby-server-deb_4.9.5.0_amd64.deb";
      sha256 = "sha256-HXGP+gFpw5PePq/aZbGwV6PbTq2T/+tYg6vQFzXemEM=";
    };
  };
  fish_abbreviation_tips = {
    pname = "fish_abbreviation_tips";
    version = "8ed76a62bb044ba4ad8e3e6832640178880df485";
    src = fetchFromGitHub {
      owner = "Gazorby";
      repo = "fish-abbreviation-tips";
      rev = "8ed76a62bb044ba4ad8e3e6832640178880df485";
      fetchSubmodules = false;
      sha256 = "sha256-F1t81VliD+v6WEWqj1c1ehFBXzqLyumx5vV46s/FZRU=";
    };
    date = "2023-01-23";
  };
  fish_async_prompt = {
    pname = "fish_async_prompt";
    version = "4c732cc043b8dd04e64a169ec6bbf3a9b394819f";
    src = fetchFromGitHub {
      owner = "acomagu";
      repo = "fish-async-prompt";
      rev = "4c732cc043b8dd04e64a169ec6bbf3a9b394819f";
      fetchSubmodules = false;
      sha256 = "sha256-YgqZINmY4nKphlqwHo2B0NfP4nmSxIIuAMUuoftI9Lg=";
    };
    date = "2023-02-26";
  };
  fish_autopairs = {
    pname = "fish_autopairs";
    version = "4d1752ff5b39819ab58d7337c69220342e9de0e2";
    src = fetchFromGitHub {
      owner = "jorgebucaran";
      repo = "autopair.fish";
      rev = "4d1752ff5b39819ab58d7337c69220342e9de0e2";
      fetchSubmodules = false;
      sha256 = "sha256-qt3t1iKRRNuiLWiVoiAYOu+9E7jsyECyIqZJ/oRIT1A=";
    };
    date = "2022-07-04";
  };
  fish_brew = {
    pname = "fish_brew";
    version = "328fc82e1c8e6fd5edc539de07e954230a9f2cef";
    src = fetchFromGitHub {
      owner = "oh-my-fish";
      repo = "plugin-brew";
      rev = "328fc82e1c8e6fd5edc539de07e954230a9f2cef";
      fetchSubmodules = false;
      sha256 = "sha256-ny82EAz0K4XYASEP/K8oxyhyumrITwC5lLRd+HScmNQ=";
    };
    date = "2023-05-11";
  };
  fish_done = {
    pname = "fish_done";
    version = "b86292a52a2b8f646ef8d25daa3cc01ccab60b62";
    src = fetchFromGitHub {
      owner = "franciscolourenco";
      repo = "done";
      rev = "b86292a52a2b8f646ef8d25daa3cc01ccab60b62";
      fetchSubmodules = false;
      sha256 = "sha256-Tr22ktv2tQdtV153xm2vHnll8G26abSyXD5IokMjAj0=";
    };
    date = "2026-06-15";
  };
  fish_jump = {
    pname = "fish_jump";
    version = "af285ff91fa9d0d0261b810e09f8a4a05a6b1307";
    src = fetchFromGitHub {
      owner = "oh-my-fish";
      repo = "plugin-jump";
      rev = "af285ff91fa9d0d0261b810e09f8a4a05a6b1307";
      fetchSubmodules = false;
      sha256 = "sha256-MVIXBKsfd7rrH7Dh7cksNI29YunqAGZvuZwdfrf1bZQ=";
    };
    date = "2021-02-14";
  };
  fish_puffer_fish = {
    pname = "fish_puffer_fish";
    version = "83174b07de60078be79985ef6123d903329622b8";
    src = fetchFromGitHub {
      owner = "nickeb96";
      repo = "puffer-fish";
      rev = "83174b07de60078be79985ef6123d903329622b8";
      fetchSubmodules = false;
      sha256 = "sha256-Dhx5+XRxJvlhdnFyimNxFyFiASrGU4ZwyefsDwtKnSg=";
    };
    date = "2025-11-13";
  };
  fish_sponge = {
    pname = "fish_sponge";
    version = "384299545104d5256648cee9d8b117aaa9a6d7be";
    src = fetchFromGitHub {
      owner = "meaningful-ooo";
      repo = "sponge";
      rev = "384299545104d5256648cee9d8b117aaa9a6d7be";
      fetchSubmodules = false;
      sha256 = "sha256-MdcZUDRtNJdiyo2l9o5ma7nAX84xEJbGFhAVhK+Zm1w=";
    };
    date = "2022-10-05";
  };
  fish_sudope = {
    pname = "fish_sudope";
    version = "4ad91e49329811939c3a09221a95e620c3964b17";
    src = fetchFromGitHub {
      owner = "oh-my-fish";
      repo = "plugin-sudope";
      rev = "4ad91e49329811939c3a09221a95e620c3964b17";
      fetchSubmodules = false;
      sha256 = "sha256-OsgThGY/tGF/XBQFyXTY9qYf50B01wEH93lqWEAxZPY=";
    };
    date = "2025-09-16";
  };
  fuzzy-pkg-finder = {
    pname = "fuzzy-pkg-finder";
    version = "1b3e34130de6a0b3bcdf4646d944d9da76dcd588";
    src = fetchFromGitHub {
      owner = "ericlay";
      repo = "fuzzy-pkg-finder";
      rev = "1b3e34130de6a0b3bcdf4646d944d9da76dcd588";
      fetchSubmodules = false;
      sha256 = "sha256-auyW6VqnHJToMpc695C4sLzed/R9i/Wmn0C2n3V3jOk=";
    };
    date = "2024-12-11";
  };
  hermes_lcm = {
    pname = "hermes_lcm";
    version = "v0.10.4";
    src = fetchFromGitHub {
      owner = "stephenschoettler";
      repo = "hermes-lcm";
      rev = "v0.10.4";
      fetchSubmodules = false;
      sha256 = "sha256-14phNk0DJDKpPwYAjm8RaJCE4g0KiRNhjc7rAI4h9n4=";
    };
  };
  sbarlua = {
    pname = "sbarlua";
    version = "dba9cc421b868c918d5c23c408544a28aadf2f2f";
    src = fetchFromGitHub {
      owner = "FelixKratz";
      repo = "SbarLua";
      rev = "dba9cc421b868c918d5c23c408544a28aadf2f2f";
      fetchSubmodules = false;
      sha256 = "sha256-lhLTrdufA3ALJ2S5HLdgNOr5seWIWEHkVhZNPObzbvI=";
    };
    date = "2026-03-06";
  };
  vicinae_extensions = {
    pname = "vicinae_extensions";
    version = "b2169756872919f2bdeece9bce47247ba5d99b8a";
    src = fetchFromGitHub {
      owner = "vicinaehq";
      repo = "extensions";
      rev = "b2169756872919f2bdeece9bce47247ba5d99b8a";
      fetchSubmodules = false;
      sha256 = "sha256-9D3/tZiIUUqNEVs0zdEgdTkY6qS70qbV87+KrXWiwV4=";
    };
    date = "2026-06-09";
  };
  yazi_flavors = {
    pname = "yazi_flavors";
    version = "ea32808e301126e1b4cf909d84123eed71ff1f01";
    src = fetchFromGitHub {
      owner = "PhotonQuantum";
      repo = "flavors";
      rev = "ea32808e301126e1b4cf909d84123eed71ff1f01";
      fetchSubmodules = false;
      sha256 = "sha256-MTVv6/zzLo9377GuFqDiJV4u4XaCe0vEhLIgcn/wmzI=";
    };
    date = "2026-05-17";
  };
  zimfw_completion = {
    pname = "zimfw_completion";
    version = "8d3e0f4e6272f4d3bad659eaa13929f9dd96f123";
    src = fetchFromGitHub {
      owner = "zimfw";
      repo = "completion";
      rev = "8d3e0f4e6272f4d3bad659eaa13929f9dd96f123";
      fetchSubmodules = false;
      sha256 = "sha256-xBurErM7KMMDObN3zPwTSOvKqXl9FDZxGfxugwlX/fk=";
    };
    date = "2026-03-27";
  };
  zimfw_git = {
    pname = "zimfw_git";
    version = "fff448c0b89a4885f4ace90e2f37893a078b0c8a";
    src = fetchFromGitHub {
      owner = "zimfw";
      repo = "git";
      rev = "fff448c0b89a4885f4ace90e2f37893a078b0c8a";
      fetchSubmodules = false;
      sha256 = "sha256-ojcv6nCOcv+2bbOZxcWhiefQ6mIWovYV57K8V6iyO5M=";
    };
    date = "2026-01-05";
  };
  zimfw_input = {
    pname = "zimfw_input";
    version = "bdec2b372f8bd16a072d30ebc447a22dad52cfb4";
    src = fetchFromGitHub {
      owner = "zimfw";
      repo = "input";
      rev = "bdec2b372f8bd16a072d30ebc447a22dad52cfb4";
      fetchSubmodules = false;
      sha256 = "sha256-/tWks6oFH6/LK8u9SxsZIJ9uAonJ2T6l91BflDwog80=";
    };
    date = "2026-06-08";
  };
  zimfw_utility = {
    pname = "zimfw_utility";
    version = "e1d1c23f578420e285cbea41dbd5cef75b35ca5b";
    src = fetchFromGitHub {
      owner = "zimfw";
      repo = "utility";
      rev = "e1d1c23f578420e285cbea41dbd5cef75b35ca5b";
      fetchSubmodules = false;
      sha256 = "sha256-2V3GYtfEtHwU8ba7pd9gQykUjp+yI0UBmxSOnHQdXNM=";
    };
    date = "2026-01-05";
  };
  zsh_completions = {
    pname = "zsh_completions";
    version = "03bae0bf3f9c4ab894f1f11a31ffe7a1e1029879";
    src = fetchFromGitHub {
      owner = "zsh-users";
      repo = "zsh-completions";
      rev = "03bae0bf3f9c4ab894f1f11a31ffe7a1e1029879";
      fetchSubmodules = false;
      sha256 = "sha256-lRRmX3aNTmFu2zjSIROL0XUfkKN6dpsOpLPIVMtqijQ=";
    };
    date = "2026-06-26";
  };
}
