# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  zimfw_completion = {
    pname = "zimfw_completion";
    version = "6a78111576cd0c653e0fbeb1ead5d2de3b490440";
    src = fetchFromGitHub ({
      owner = "zimfw";
      repo = "completion";
      rev = "6a78111576cd0c653e0fbeb1ead5d2de3b490440";
      fetchSubmodules = false;
      sha256 = "sha256-dFFkeQkoGpi4aJkkq4gXExcAKLN/XtwvqT6TRA09nnA=";
    });
  };
  zimfw_git = {
    pname = "zimfw_git";
    version = "ecd06b6ac9ef0fcfc333331ab891043dcc5cf311";
    src = fetchFromGitHub ({
      owner = "zimfw";
      repo = "git";
      rev = "ecd06b6ac9ef0fcfc333331ab891043dcc5cf311";
      fetchSubmodules = false;
      sha256 = "sha256-i66Yyx9BehGMnc2j31JcFe5jxqJSdO/546IxifH8MCc=";
    });
  };
  zimfw_input = {
    pname = "zimfw_input";
    version = "bcff8c8504ea7efd0fc8c696dfdc8762e4bfbbb6";
    src = fetchFromGitHub ({
      owner = "zimfw";
      repo = "input";
      rev = "bcff8c8504ea7efd0fc8c696dfdc8762e4bfbbb6";
      fetchSubmodules = false;
      sha256 = "sha256-jH1aTY7vvbA5zygdwUhOloREwjOPftXU/GGuxElTvFE=";
    });
  };
  zimfw_utility = {
    pname = "zimfw_utility";
    version = "2696a4da0dfb901753f92c071437606c5156cc0f";
    src = fetchFromGitHub ({
      owner = "zimfw";
      repo = "utility";
      rev = "2696a4da0dfb901753f92c071437606c5156cc0f";
      fetchSubmodules = false;
      sha256 = "sha256-GmiaToncT/C4/qoN+9ierFY54FGZejUvlomDZoi9qH8=";
    });
  };
  zsh_completions = {
    pname = "zsh_completions";
    version = "45b5a8a78da4d9b0228e69b23867a8ecf0f42f5e";
    src = fetchFromGitHub ({
      owner = "zsh-users";
      repo = "zsh-completions";
      rev = "45b5a8a78da4d9b0228e69b23867a8ecf0f42f5e";
      fetchSubmodules = false;
      sha256 = "sha256-NXERzZqG0pQrwqm9uedOpf5xcD/As4LAd4bVVsT6m4w=";
    });
  };
}
