# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, modulesPath, lib, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      ./incus.nix
      # Include the OrbStack-specific configuration.
      ./orbstack.nix

      ../common/cache.nix
    ];

  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    truested-users = [ "@wheel" ];
  };

  nixpkgs.config = {
    allowUnfree = true;
    allowUnfreePredicate = _: true;
  };

  environment.systemPackages = with pkgs; [
    # Flakes clones its dependencies through the git command,
    # so git must be installed first
    git
    vim
    wget
    ripgrep
  ];

  programs.fish.enable = true;

  environment = {
    shells = [ pkgs.fish ]; # Default shell
    variables = {
      # System variables
      SHELL = lib.getExe pkgs.fish;
      EDITOR = "nvim";
      VISUAL = "nvim";
    };
  };

  users.users.lightquantum = {
    uid = 501;
    extraGroups = [ "wheel" "orbstack" ];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/lightquantum";
    homeMode = "700";
    useDefaultShell = true;
    shell = pkgs.fish;
  };

  security.sudo.wheelNeedsPassword = false;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "America/Toronto";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Extra certificates from OrbStack.
  security.pki.certificates = [
    ''
      -----BEGIN CERTIFICATE-----
MIIBpDCCAUmgAwIBAgIQDH4yqRp5xFfPrFygWMjKTDAKBggqhkjOPQQDAjAwMS4w
LAYDVQQDEyVDYWRkeSBMb2NhbCBBdXRob3JpdHkgLSAyMDIzIEVDQyBSb290MB4X
DTIzMDYwNzA1NDc0NVoXDTMzMDQxNTA1NDc0NVowMDEuMCwGA1UEAxMlQ2FkZHkg
TG9jYWwgQXV0aG9yaXR5IC0gMjAyMyBFQ0MgUm9vdDBZMBMGByqGSM49AgEGCCqG
SM49AwEHA0IABJEUMMPjLvPnuhtpHqkDw/5eTIT8Ss5iZ6EoFWkZbtGpN2OGTSIY
hoVUMMQOvBz2JQGV/5WKtSk40kjDGMzZv0qjRTBDMA4GA1UdDwEB/wQEAwIBBjAS
BgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBTSNCX+OrJbx1rTAtse4kq06PX5
dTAKBggqhkjOPQQDAgNJADBGAiEA8CUcoiu4+j+V2fNLhIqTeLVahAS8humpGWq6
PB+WXowCIQDqhNORgPca6HpExyfkIR0OFFcGczdXoPO8HUFnIyUhkw==
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIDKDCCAhCgAwIBAgIRAMnZFeiK8LCcj+/w81PIFq0wDQYJKoZIhvcNAQELBQAw
PTELMAkGA1UEBhMCRU4xEDAOBgNVBAoMB0FkR3VhcmQxHDAaBgNVBAMME0FkZ3Vh
cmQgUGVyc29uYWwgQ0EwHhcNMjQxMDMxMTk0MjA1WhcNNDQxMDI2MTk0MjA1WjA9
MQswCQYDVQQGEwJFTjEQMA4GA1UECgwHQWRHdWFyZDEcMBoGA1UEAwwTQWRndWFy
ZCBQZXJzb25hbCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMUJ
aKzLXD+48uUvl/CG1tXUiVNp7QZHJ0T3RfwB1tVlNCfYVpPR7vi0D2UFlI19KsN/
Hu9kHV3WJ5NRPOtN7p//fyB67VX4bMICXS9kuuX8T2j95JUI6AkqbKB1z+sq4175
K2WZI3GpvE9fuum9jSLNYXNnty5AlEn3ne6gHE3bD3X72zbCsKvdmT/x7sm8KqKS
GN07/1eOiE8tQZrJbtI6hlnQAqs2yhF5sqLDWZ1+TPeGvEA7EuLFK58ZWPIUfY3M
EqJGnMbAJwKRWmih9z7FY0YJh3FFizSJZxM9Gj1wJg0P3DhCckkcI7mmSTU74uTG
DD6E+r3hns9WOang+zMCAwEAAaMjMCEwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8B
Af8EBAMCAQYwDQYJKoZIhvcNAQELBQADggEBALPBLHQbRtsszVX2YITn2YwaoNcM
7q6KyO6aMHgbBuyeDA6KysyoV+bIt8LcNIqg5AElrUuZtdfrra+VwUFKtLiuX6Ij
8gcRjWSEONWZ386D4HVpHS9vkTJZcER0wttcCJbcysKM9PMpucsUZyXhdZeORy/r
Z5yw6f8Kq3WMo5tipX0PG0DE8UAGdbENJvqj68hifEau+TMHoL5w7K8rcJ6JrHTQ
hqruF6/K68mCpNsBAuCq/nGfrCJQ5xAKXDbkpBCejmHzVM8FhC9DWiUl1dINr5NQ
GCtxtnB42rGFfDtXQhmLxuADsn93kdDESQtXZiQaV1X2udoxjJS9a0ckKlY=
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIICCzCCAbKgAwIBAgIQWbw7n9oyTJD+PUB9V8ZcEDAKBggqhkjOPQQDAjBmMR0w
GwYDVQQKExRPcmJTdGFjayBEZXZlbG9wbWVudDEeMBwGA1UECwwVQ29udGFpbmVy
cyAmIFNlcnZpY2VzMSUwIwYDVQQDExxPcmJTdGFjayBEZXZlbG9wbWVudCBSb290
IENBMB4XDTI0MDEwOTE3MzUyMVoXDTM0MDEwOTE3MzUyMVowZjEdMBsGA1UEChMU
T3JiU3RhY2sgRGV2ZWxvcG1lbnQxHjAcBgNVBAsMFUNvbnRhaW5lcnMgJiBTZXJ2
aWNlczElMCMGA1UEAxMcT3JiU3RhY2sgRGV2ZWxvcG1lbnQgUm9vdCBDQTBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABPrZt6DXu0J/J+jKtH0Q+ZhpqUnTovS+NHmJ
noAbSoe0lk45yY15cEsO0fxzQzJ1+dTyqbEqEOfA/+XXlXdlwZujQjBAMA4GA1Ud
DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQ/GxQbLZi9e52z
Who3pQ1x3SqobzAKBggqhkjOPQQDAgNHADBEAiAp9heyY/RmEnhbsAhZ1WqOglSM
9J0fPFI+9603LO+ZmAIgaMZBAmktKWnkyxAe4IkSdJLIogRoEk35i/98oXUPlus=
-----END CERTIFICATE-----

    ''
  ];

  # This option defines the first version of NixOS you have installed on this particular machine,
  # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
  #
  # Most users should NEVER change this value after the initial install, for any reason,
  # even if you've upgraded your system to a new NixOS release.
  #
  # This value does NOT affect the Nixpkgs version your packages and OS are pulled from,
  # so changing it will NOT upgrade your system - see https://nixos.org/manual/nixos/stable/#sec-upgrading for how
  # to actually do that.
  #
  # This value being lower than the current NixOS release does NOT mean your system is
  # out of date, out of support, or vulnerable.
  #
  # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
  # and migrated your data accordingly.
  #
  # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "25.05"; # Did you read the comment?
}